["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
empire = [
    "contracts/empire.cairo",
]

["protostar.test"]
cairo-path = [
    "./tests/"
]
