["protostar.config"]
protostar_version = "0.4.2"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
empire = [
    "contracts/empire.cairo",
]
erc20 = [
    "./lib/cairo_contracts_git/src/openzeppelin/token/erc20/presets/ERC20Mintable.cairo"
]
s_erc721= [
    "./lib/realms_contracts_git/contracts/settling_game/tokens/S_Realms_ERC721_Mintable.cairo"
]

["protostar.test"]
cairo-path = [
    "./tests/",
    "./lib/cairo_contracts_git/src",
]

["protostar.build"]
cairo-path = [
    "./tests/",
    "./lib/cairo_contracts_git/src",
]
